export const categoryData = [
  {
    name: "Plantas frutales",
    description:
      "Frutales autóctonos y tropicales para clima andino y jardinería de huerta.",
    products: [
      { title: "Naranja", subtitle: "Cítrico dulce", price: null, details: "Ideal para jugos y producción familiar.", image: "", stock: null },
      { title: "Mandarina", subtitle: "Cítrico aromático", price: null, details: "Muy resistente y perfecto para cultivos de pequeña escala.", image: "", stock: null },
      { title: "Durazno", subtitle: "Fruta de pulpa suave", price: null, details: "Crece bien en climas templados con buena ventilación.", image: "", stock: null },
      { title: "Manzana", subtitle: "Manzano tradicional", price: null, details: "Variedad ideal para producción casera en altura.", image: "", stock: null },
      { title: "Ciruela (Claudia)", subtitle: "Fruta de mesa", price: null, details: "Planta de fruta dulce con excelente rendimiento.", image: "", stock: null },
      { title: "Pera", subtitle: "Pera jugosa", price: null, details: "Planta de huerto que produce frutos tiernos y dulces.", image: "", stock: null },
      { title: "Cereza", subtitle: "Fruta pequeña", price: null, details: "Perfecta para jardines con clima fresco y buena exposición solar.", image: "", stock: null },
      { title: "Guaba", subtitle: "Leguminosa frutal", price: null, details: "Fruto típico de la región ideal para consumo fresco.", image: "", stock: null },
      { title: "Mango", subtitle: "Frutal tropical", price: null, details: "Requiere clima cálido en lugares protegidos o invernadero.", image: "", stock: null },
      { title: "Tocte (nogal / nuez)", subtitle: "Árbol de nueces", price: null, details: "Planta de crecimiento lento con frutos nutritivos.", image: "", stock: null },
      { title: "Naranjilla", subtitle: "Fruta exótica", price: null, details: "Planta de fruto ácido apreciada para jugos.", image: "", stock: null },
      { title: "Guayaba", subtitle: "Fruta tropical", price: null, details: "Ideal para consumo fresco y procesados dulces.", image: "", stock: null },
      { title: "Guayabilla", subtitle: "Variedad local", price: null, details: "Planta de fruto pequeño muy sabroso.", image: "", stock: null },
      { title: "Fresa", subtitle: "Fruta roja", price: null, details: "Planta ideal para macetas y bandejas flotantes.", image: "", stock: null },
      { title: "Frambuesa", subtitle: "Pequeña y aromática", price: null, details: "Planta ornamental y comestible con frutos suaves.", image: "", stock: null },
      { title: "Uva", subtitle: "Vid para jardín", price: null, details: "Requiere soporte y exposición al sol.", image: "", stock: null },
      { title: "Granadilla", subtitle: "Fruta de pulpa aromática", price: null, details: "Planta trepadora que necesita tutor y clima frío.", image: "", stock: null },
      { title: "Tomate de árbol", subtitle: "Fruta andina", price: null, details: "Planta alta que produce frutos nutritivos y ácidos.", image: "", stock: null },
      { title: "Tomate riñón", subtitle: "Tomate para ensaladas", price: null, details: "Variedad de fruto firme y sabroso.", image: "", stock: null },
      { title: "Tomate cherry", subtitle: "Tomate pequeño", price: null, details: "Excelente para cultivo en macetas y consumo fresco.", image: "", stock: null },
      { title: "Chirimoya", subtitle: "Fruta tropical", price: null, details: "Planta de clima templado con frutos cremosos.", image: "", stock: null },
    ],
  },
  {
    name: "Plantas medicinales / aromáticas",
    description: "Especies útiles para remedios caseros, infusiones y aromatizar espacios.",
    products: [
      { title: "Ruda", subtitle: "Planta medicinal", price: null, details: "Usada para infusiones y tradición herbal.", image: "", stock: null },
      { title: "Sábila", subtitle: "Aloe vera", price: null, details: "Muy utilizada para cuidado de la piel.", image: "", stock: null },
      { title: "Menta", subtitle: "Hierba aromática", price: null, details: "Ideal para infusiones y aromatizar ambientes.", image: "", stock: null },
      { title: "Cedro", subtitle: "Aromático y medicinal", price: null, details: "Planta de hojas fragantes y usos tradicionales.", image: "", stock: null },
      { title: "Hierba Luisa", subtitle: "Limoncillo", price: null, details: "Planta aromática para té digestivo.", image: "", stock: null },
      { title: "Toronjil", subtitle: "Melisa", price: null, details: "Planta calmante ideal para infusiones.", image: "", stock: null },
      { title: "Albahaca", subtitle: "Hierba culinaria", price: null, details: "Muy usada en cocina y en jardines aromáticos.", image: "", stock: null },
      { title: "Apio", subtitle: "Hierba comestible", price: null, details: "Planta versátil para ensaladas y guisos.", image: "", stock: null },
      { title: "Dulcamara", subtitle: "Hierba medicinal", price: null, details: "Usada en tradición herbal y jardinería natural.", image: "", stock: null },
      { title: "Orégano orejón", subtitle: "Aromático", price: null, details: "Variedad de orégano con hojas grandes y fragantes.", image: "", stock: null },
      { title: "Orégano (normal)", subtitle: "Aromático clásico", price: null, details: "Ideal para cocinar y para huertos caseros.", image: "", stock: null },
    ],
  },
  {
    name: "Plantas nativas",
    description: "Especies autóctonas valiosas para la reforestación y jardines naturales.",
    products: [
      { title: "Cholán", subtitle: "Planta nativa", price: null, details: "Especie local para paisajismo y recuperación de suelos.", image: "", stock: null },
      { title: "Laurel", subtitle: "Árbol aromático", price: null, details: "Árbol tradicional con múltiples usos culturales.", image: "", stock: null },
      { title: "Floripondio", subtitle: "Flor ornamental", price: null, details: "Planta llamativa con flores grandes y fragantes.", image: "", stock: null },
      { title: "Aliso", subtitle: "Árbol de ribera", price: null, details: "Ideal para zonas húmedas y control de erosión.", image: "", stock: null },
    ],
  },
  {
    name: "Plantas ornamentales (flores)",
    description: "Flores y plantas decorativas para jardines, patios y balcones.",
    products: [
      { title: "Geranios", subtitle: "Planta de flor", price: null, details: "Colorida y resistente, perfecta para macetas.", image: "", stock: null },
      { title: "Begonias", subtitle: "Flores ornamentales", price: null, details: "Ideal para interiores y sombras ligeras.", image: "", stock: null },
      { title: "Claveles", subtitle: "Flor clásica", price: null, details: "Fácil de cultivar y con flores duraderas.", image: "", stock: null },
      { title: "Margaritas", subtitle: "Planta campestre", price: null, details: "Aporta luz y frescura en camas florales.", image: "", stock: null },
      { title: "Ciclamen", subtitle: "Flor de interior", price: null, details: "Popular en ambientes frescos y con flores coloridas.", image: "", stock: null },
      { title: "Pensamientos", subtitle: "Planta de estación", price: null, details: "Resistente y ideal para borduras y macetas.", image: "", stock: null },
      { title: "Dormilonas", subtitle: "Victoria regia", price: null, details: "Florece en climas fríos con pétalos suaves.", image: "", stock: null },
      { title: "Clavelina", subtitle: "Planta ornamental", price: null, details: "Compacta y con flores delicadas.", image: "", stock: null },
    ],
  },
  {
    name: "Cactus",
    description: "Plantas suculentas de bajo mantenimiento para espacios interiores y exteriores.",
    products: [
      { title: "Cactus (variedad general)", subtitle: "Suculeta mixta", price: null, details: "Colección de cactus resistentes y de fácil cuidado.", image: "", stock: null },
    ],
  },
  {
    name: "Plantas de jardín / decoración exterior",
    description: "Especies para darle estructura y frescura a jardines y terrazas.",
    products: [
      { title: "Duranta", subtitle: "Arbusto florido", price: null, details: "Ideal para setos y separadores verdes.", image: "", stock: null },
      { title: "Palmeras", subtitle: "Planta vertical", price: null, details: "Perfecta para dar altura y sombra al jardín.", image: "", stock: null },
      { title: "Plantas colgantes", subtitle: "Decoración aérea", price: null, details: "Dale movimiento a balcones y pérgolas.", image: "", stock: null },
      { title: "Helechos", subtitle: "Verde abundante", price: null, details: "Plantas ideales para zonas sombreadas y húmedas.", image: "", stock: null },
    ],
  },
  {
    name: "Hortalizas",
    description: "Verduras y plantas de huerto para cosechas frescas en tu hogar.",
    products: [
      { title: "Lechuga", subtitle: "Hoja fresca", price: null, details: "Rápido crecimiento y cosecha continua.", image: "", stock: null },
      { title: "Col", subtitle: "Brassica", price: null, details: "Planta robusta para clima templado.", image: "", stock: null },
      { title: "Brócoli", subtitle: "Verdura saludable", price: null, details: "Ideal para huertos familiares y consumo directo.", image: "", stock: null },
      { title: "Remolacha", subtitle: "Raíz nutritiva", price: null, details: "Planta de raíz dulce y hojas comestibles.", image: "", stock: null },
      { title: "Cebolla larga", subtitle: "Cebolla tierna", price: null, details: "Perfecta para ensaladas y condimentos.", image: "", stock: null },
      { title: "Cebolla paiteña", subtitle: "Variedad local", price: null, details: "Cebolla tradicional de la región con sabor fuerte.", image: "", stock: null },
      { title: "Alfalfa", subtitle: "Forrajera", price: null, details: "Planta rica en nutrientes para alimentación natural.", image: "", stock: null },
      { title: "Apio", subtitle: "Hierba crujiente", price: null, details: "Ideal para huertos y ensaladas frescas.", image: "", stock: null },
      { title: "Perejil", subtitle: "Hierba aromática", price: null, details: "Perfecto para acompañar platos y salsas.", image: "", stock: null },
      { title: "Cilantro", subtitle: "Hierba fresca", price: null, details: "Usado en cocina tradicional y huertos de balcón.", image: "", stock: null },
      { title: "Papa", subtitle: "Tubérculo", price: null, details: "Planta de raíz para huertos familiares y cocina diaria.", image: "", stock: null },
      { title: "Nabo", subtitle: "Raíz fresca", price: null, details: "Especie perfecta para clima fresco y rotación de cultivos.", image: "", stock: null },
      { title: "Nabo chino", subtitle: "Daikon", price: null, details: "Variedad de nabo ideal para siembras en maceta.", image: "", stock: null },
    ],
  },
];
